/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.SystemAdminWorkArea;

import Code.Directory_Address;
import Code.EcoSystem;
import Code.EnterPrise;
import Code.Network;
import Code.Organization.Organization;
import java.awt.CardLayout;
import static java.time.Clock.system;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author saich
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
JPanel userContainer;
EcoSystem eco;
private Directory_Address addresslist;
    public SystemAdminWorkAreaJPanel(JPanel userContainer, EcoSystem eco) {
        initComponents();
        this.userContainer = userContainer;
        this.eco =eco;
        populateTreewithData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        BtnManageNET = new javax.swing.JButton();
        BTNEnterPrise = new javax.swing.JButton();
        BTNEnterPriseAdmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.add(jScrollPane1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Network");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Enterprise");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Enterprise Admin");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Reports");
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTree1);

        jPanel2.add(jScrollPane2);

        BtnManageNET.setText("Manage Network");
        BtnManageNET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageNETActionPerformed(evt);
            }
        });

        BTNEnterPrise.setText("Manage Enterprise");
        BTNEnterPrise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEnterPriseActionPerformed(evt);
            }
        });

        BTNEnterPriseAdmin.setText("Manage Enterprise Admin");
        BTNEnterPriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEnterPriseAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNEnterPriseAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNEnterPrise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnManageNET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(BtnManageNET)
                        .addGap(18, 18, 18)
                        .addComponent(BTNEnterPrise)
                        .addGap(18, 18, 18)
                        .addComponent(BTNEnterPriseAdmin)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnManageNETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageNETActionPerformed
        ManageNetworkJPanel manageNtwrkJPnl = new ManageNetworkJPanel(userContainer,eco);
        userContainer.add("manageNtwrkJPnl",manageNtwrkJPnl);
        CardLayout crdlyt = (CardLayout) userContainer.getLayout();
        crdlyt.next(userContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnManageNETActionPerformed

    private void BTNEnterPriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEnterPriseActionPerformed
        ManageEnterpiseJPanel mngEntJPanel = new  ManageEnterpiseJPanel(userContainer, eco);
        userContainer.add("mngEntJPanel", mngEntJPanel);
        CardLayout crdlyt = (CardLayout) userContainer.getLayout();
        crdlyt.next(userContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEnterPriseActionPerformed

    private void BTNEnterPriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEnterPriseAdminActionPerformed
        ManageEnterpriseAdminJPanel manageAdminJPnl = new ManageEnterpriseAdminJPanel(userContainer,eco);
        userContainer.add("manageNtwrkJPnl",manageAdminJPnl);
        CardLayout crdlyt = (CardLayout) userContainer.getLayout();
        crdlyt.next(userContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEnterPriseAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEnterPrise;
    private javax.swing.JButton BTNEnterPriseAdmin;
    private javax.swing.JButton BtnManageNET;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    private void populateTreewithData() {
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
      DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();



        ArrayList<Network> networkList = eco.getNetworks();
        ArrayList<EnterPrise> enterpriseList;
        ArrayList<Organization> organizationList;
        Network network;
        EnterPrise enterprise;
        Organization organization;



        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);



        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        for (int i = 0; i < networkList.size(); i++) {
        network = networkList.get(i);
        networkNode = new DefaultMutableTreeNode(network.getNetwork_Name());
        networks.insert(networkNode, i);



        enterpriseList = network.getDirectoEnterpri().getEnterpList();



        for (int j = 0; j < enterpriseList.size(); j++) {
        enterprise = enterpriseList.get(j);
        enterpriseNode = new DefaultMutableTreeNode(enterprise.getOrgName());
        networkNode.insert(enterpriseNode, j);



        organizationList = enterprise.getOrgaDirectory().getOrganizations();
        for (int k = 0; k < organizationList.size(); k++) {
        organization = organizationList.get(k);
        organizationNode = new DefaultMutableTreeNode(organization.getOrgName());
        enterpriseNode.insert(organizationNode, k);
        }
        }
        }
        model.reload();
    }
}
