/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Doctor;

import Code.Account;
import Code.Doctor;
import Code.EcoSystem;
import Code.EnterPrise;
import Code.Network;
import Code.Organization.Organization_Doctor;
import Code.PrescriptionList;
import Code.WorkQueue.DoctorWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author saich
 */
public class Doctor_WorkArea extends javax.swing.JPanel {



private JPanel userContainer;
private Organization_Doctor org_doc;
private Account ua;
private EnterPrise enter;
private Doctor doctor;
private PrescriptionList p_list;
private DoctorWorkRequest dwr ;
private Network network;
private EcoSystem ecosystem;




    /**
     * Creates new form Doctor_WorkArea
     * @param 
     */
    public Doctor_WorkArea(JPanel userContainer,
Account ua,
Organization_Doctor org_doc,
 EnterPrise enter,
EcoSystem ecosystem,
Network network
) {
        initComponents();
this.userContainer = userContainer;
this.ua = ua ;
this.network = network;
this.org_doc = org_doc;
this.enter = enter;
this.ecosystem = ecosystem;
network();




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Pres_Button = new javax.swing.JButton();
        Manage_Equipment_Button = new javax.swing.JButton();

        jLabel1.setText("Doctor Work Area");

        Pres_Button.setText("Precribe Medicine");
        Pres_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pres_ButtonActionPerformed(evt);
            }
        });

        Manage_Equipment_Button.setText("Manage_Equipment");
        Manage_Equipment_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_Equipment_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Pres_Button)
                        .addGap(76, 76, 76)
                        .addComponent(Manage_Equipment_Button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pres_Button)
                    .addComponent(Manage_Equipment_Button))
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Manage_Equipment_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Equipment_ButtonActionPerformed
        // TODO add your handling code here:
CardLayout abs = (CardLayout)userContainer.getLayout();
userContainer.add("PrescriptionJPanel", new UserInterface.Doctor.HealthCareEquipmentManagementJpanel(userContainer, ua,org_doc,enter,ecosystem,network));
abs.next(userContainer);
    }//GEN-LAST:event_Manage_Equipment_ButtonActionPerformed

    private void Pres_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pres_ButtonActionPerformed
        // TODO add your handling code here:
CardLayout abs = (CardLayout)userContainer.getLayout();
userContainer.add("PrescriptionJPanel", new UserInterface.Doctor.PrescriptionJPanel(userContainer,p_list,ua,enter,org_doc));
abs.next(userContainer);
    }//GEN-LAST:event_Pres_ButtonActionPerformed

private void network(){
network.getNetwork_Name();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Manage_Equipment_Button;
    private javax.swing.JButton Pres_Button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
