/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.HealthCareEquipmentAdmin;

import Code.EnterPrise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author saich
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
 JPanel uppercontainer;
 EnterPrise enter;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel uppercontainer, EnterPrise enter ) {
        initComponents();
this.uppercontainer = uppercontainer;
this.enter = enter;
jlbl2.setText(enter.getOrgName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JLabel();
        jlbl1 = new javax.swing.JLabel();
        jlbl2 = new javax.swing.JLabel();
        OrgManageBtn = new javax.swing.JButton();
        ManageEmployeeBtn = new javax.swing.JButton();
        ManageUserBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        Header.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Header.setText("MY Work Area - Administrative Role");

        jlbl1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbl1.setText("Enterprise : ");

        jlbl2.setText("<Value>");

        OrgManageBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrgManageBtn.setText("Manage Organization");
        OrgManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrgManageBtnActionPerformed(evt);
            }
        });

        ManageEmployeeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageEmployeeBtn.setText("Manage Employee");
        ManageEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEmployeeBtnActionPerformed(evt);
            }
        });

        ManageUserBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageUserBtn.setText("Manage User");
        ManageUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManageUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrgManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(110, 241, Short.MAX_VALUE)
                    .addComponent(jlbl1)
                    .addGap(30, 30, 30)
                    .addComponent(jlbl2)
                    .addGap(0, 548, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(OrgManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ManageEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ManageUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 193, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbl1)
                        .addComponent(jlbl2))
                    .addGap(0, 353, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OrgManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrgManageBtnActionPerformed
        ManageOrganizationJPanel manageOrgJPanel = new ManageOrganizationJPanel(uppercontainer, enter.getOrgaDirectory());
        uppercontainer.add("manageOrgJPanel", manageOrgJPanel);
        CardLayout layout = (CardLayout) uppercontainer.getLayout();
        layout.next(uppercontainer);
    }//GEN-LAST:event_OrgManageBtnActionPerformed

    private void ManageEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEmployeeBtnActionPerformed
        // TODO add your handling code here:
         ManageEmployeeJPanel manageemployeeJPanel = new ManageEmployeeJPanel(uppercontainer, enter.getOrgaDirectory());
         uppercontainer.add("manageemployeeJPanel",manageemployeeJPanel );
        CardLayout layout = (CardLayout) uppercontainer.getLayout();
        layout.next(uppercontainer);
    }//GEN-LAST:event_ManageEmployeeBtnActionPerformed

    private void ManageUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserBtnActionPerformed
        // TODO add your handling code here:
ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(uppercontainer, enter);
         uppercontainer.add("ManageUserAccountJPanel",muajp );
        CardLayout layout = (CardLayout) uppercontainer.getLayout();
        layout.next(uppercontainer);
    }//GEN-LAST:event_ManageUserBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    private javax.swing.JButton ManageEmployeeBtn;
    private javax.swing.JButton ManageUserBtn;
    private javax.swing.JButton OrgManageBtn;
    private javax.swing.JLabel jlbl1;
    private javax.swing.JLabel jlbl2;
    // End of variables declaration//GEN-END:variables
}
